<?php

/*
	Do not edit this file manually. This copy of global file is overwritten
	by extensions editor.
*/

$installed_extensions = array (
  1 => 
  array (
    'name' => 'zen_import',
    'package' => 'zen_import',
    'version' => '2.4.0-1',
    'type' => 'extension',
    'active' => false,
    'path' => 'modules/zen_import',
  ),
  3 => 
  array (
    'package' => 'HumanResourceManagement',
    'name' => 'HumanResourceManagement',
    'version' => '2.4.0-1',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/HumanResourceManagement',
    'active' => 1,
  ),
);
